### ISSUE TITLE
Перевести главы книг на русский

### ISSUE THREAD

**Issue by VladBlow** [azat-io/you-dont-know-js-ru#13]
Начал читать, и столкнулся с тем что названия глав некоторых книг не переведены на русский, хотя сама глава переведена. Это сбивает с толку, когда заходишь в книгу, видишь главы на английском, кажется что и внутри они на английском будут. Могу посодействовать в переводе, просто ответь на issue и я сделаю пул-реквесты.

**Comment by azat-io** [comment]
Буду рад :+1:

**Comment by meowniy** [comment]
Что от меня требуется ? я ламер в гитхабе пока что)

**Comment by azat-io** [comment]
@meowniy Здесь мы занимаемся переводом серии книг. Можешь брать любую непереведённую, после чего отправляй пулл реквест
