### ISSUE TITLE
Опечатка в главе Строгий режим (Strict Mode)

### ISSUE THREAD

**Issue by obergodmar** [azat-io/you-dont-know-js-ru#133]
Вы не знаете JS: Начните и Совершенствуйтесь, Глава 2: Введение в JavaScript, Строгий режим (Strict Mode), второй абзац:

Вы можете явно указать его для отдельной функции или целого файла, в зависимости от того, где вы разместите директиву **строго** режима:

**Comment by matyushevskiy** [comment]
Вы можете явно указать его для отдельной функции или целого файла, в зависимости от того, где вы разместите директиву **строго** режима:

Всего одно ключевое отличие (улучшение!) **строго** режима — запрет автоматического неявного объявления глобальных переменных из-за пропуска var:

Если вы включаете строгий режим в своем коде и получаете ошибки, или код начинает вести себя ошибочно, у вас может возникнуть соблазн избегать **строго** режима.
