### ISSUE TITLE
Идея по исправлению

### ISSUE THREAD

**Issue by yenobi** [azat-io/you-dont-know-js-ru#15]
В третьей главе первой книги (up & going), [в этой части](https://github.com/azat-io/you-dont-know-js-ru/blob/master/up%20%26%20going/ch3.md#Асинхронность-и-производительность), использован термин "обещания", который переведен на русский. Может, как и с `this` следует использовать конструкцию `promise`? Больно уж глаз режут обещания.

**Comment by azat-io** [comment]
@yenobi Согласен, сделаешь PR?

**Comment by yenobi** [comment]
да, на днях)

**Comment by KamilOcean** [comment]
Привет, я начал переводить часть книги про замыкания, ch5, просто хочу удостовреиться в том, что её еще не переводили, а то мои старания будут напрасны.

**Comment by t0lik** [comment]
Я уже перевожу ch5.

**Comment by KamilOcean** [comment]
ну ок, я еще до этого главу исправил немного, сделаю тогда что есть pull request и там глянете, может что пригодится и в тексте опечатки из предыдущей главы
