### ISSUE TITLE
Перевод Async & Performance ch.3

### ISSUE THREAD

**Issue by t0lik** [azat-io/you-dont-know-js-ru#247]
PR: #279

**Comment by t0lik** [comment]
@azat-io можешь глянуть ПР по ссылке? Я закончил перевод, но есть пара моментов с переводом слов (см. описание) ну и в целом пробежаться и высказать свои предложения.

**Comment by azat-io** [comment]
@t0lik Откроешь ПР в этот репозиторий?

**Comment by azat-io** [comment]
Спасибо! Смержил!

**Comment by t0lik** [comment]
> Спасибо! Смержил!

А 2 вопроса по переводу слов?
