### ISSUE TITLE
Statement issues

### ISSUE THREAD

**Issue by DemjanUA** [azat-io/you-dont-know-js-ru#29]
Книжка ["up & going" Глава 1: Введение в программирование](https://github.com/azat-io/you-dont-know-js-ru/blob/master/up%20%26%20going/ch1.md#Операторы)
Термин [statement ](https://github.com/getify/You-Dont-Know-JS/blob/master/up%20%26%20going/ch1.md#statements) переведен как "Оператор", но в контексте JS
Statement - инструкция
Operator - оператор

В спецификации ES : Operator (оператор) - [разновидность выражений 
](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-ecmascript-language-expressions)

> The = and * characters are operators (see "Operators") 

А [Statement](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-ecmascript-language-statements-and-declarations) (инструкция)

> In a computer language, a group of words, numbers, and operators that performs a specific task is a statement. 

-------------
От ошибки с переводом слова Statement ошибка тут:
[Тут](https://github.com/azat-io/you-dont-know-js-ru/blob/master/up%20%26%20going/ch1.md#Условные-операторы)

В спецификации конструкцию if ( ) else называют [ifStatement](http://www.ecma-international.org/ecma-262/7.0/index.html#prod-IfStatement) то есть **инструкция условия**
[о ней и идет речь](https://github.com/azat-io/you-dont-know-js-ru/blob/master/up%20%26%20going/ch1.md#Условные-операторы), а [условные операторы](https://github.com/azat-io/you-dont-know-js-ru/blob/master/up%20%26%20going/ch1.md#Условные-операторы)  [в спецификации это тернарный оператор](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-conditional-operator) `? :`
Я советую переводить так:
Statement - **инструкция**
Operator - **оператор**
Conditionals = Conditionals statement = ifStatement = инструкции условия или просто **Условия** 
Conditional Operator (`? :`) = Условный оператор

**Comment by t0lik** [comment]
if всю жизнь оператором был, также как и for, к примеру. А они по-английски и пишутся statement. 

> The [In] grammar parameter is needed to avoid confusing the in operator in a relational expression with the in operator in a for statement
Т.е. тут речь про операцию in в операторе for.
А операциями были такие как умножение, сложение, присваивание. 

> that is, as if using the ECMAScript operators * and +

Даже в википедии:

> Инстру́кция или опера́тор (англ. statement) — наименьшая автономная часть языка программирования; команда или набор команд. Программа обычно представляет собой последовательность инструкций
>Опера́ция — конструкция в языках программирования, аналогичная по записи математическим операциям, то есть специальный способ записи некоторых действий
> Из-за путаницы с терминологией словом «оператор» в программировании нередко обозначают операцию (англ. operator), см. Операция (программирование). 
> Английское слово operator, соответствующее термину «операция», иногда ошибочно переводят как «оператор». На самом деле (по историческим причинам) русский термин «оператор» обозначает то же, что и «инструкция», которой соответствует английское statement[1]. Путаница усугубилась тем, что в C присваивание и инкремент/декремент являются и операторами, и операциями

**Comment by DemjanUA** [comment]
![image](https://cloud.githubusercontent.com/assets/16669415/25361936/ad187f0e-2959-11e7-8eb2-c89ff4d553dd.png)

**Comment by DemjanUA** [comment]
![image](https://cloud.githubusercontent.com/assets/16669415/25362120/bb8864d6-295a-11e7-97f9-43019dee2444.png)

**Comment by DemjanUA** [comment]
Согласен, If и For операторы, но aвот инструкция кроме(оператора также имеет другие части) слова
![image](https://cloud.githubusercontent.com/assets/16669415/25362362/1ac9d514-295c-11e7-97b7-526926c46790.png)

**Comment by t0lik** [comment]
Думаю, что в главе 1 надо просто заменить "conditionals" на "условные конструкции". Сейчас там три варианта перевода: инструкции, операторы и конструкции.
