### ISSUE TITLE
Глава 2

### ISSUE THREAD

**Issue by userbq201** [azat-io/you-dont-know-js-ru#72]
``В JavaScript ест два таких механизма.`` По идее имелось ввиду ``есть``. Раздел [ссылка](https://github.com/azat-io/you-dont-know-js-ru/blob/master/scope%20%26%20closures/ch2.md#%D0%9E%D0%B1%D0%BC%D0%B0%D0%BD%D1%8B%D0%B2%D0%B0%D0%B5%D0%BC-%D0%BB%D0%B5%D0%BA%D1%81%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D1%83%D1%8E-%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C-%D0%B2%D0%B8%D0%B4%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8)

**Comment by Alex-K1m** [comment]
Fixed in #85
